"""create resumes table

Revision ID: fa56b9fcee90
Revises: dcb91c46fcc6
Create Date: 2026-09-14 13:27:34.439536
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fa56b9fcee90'
down_revision: Union[str, None] = 'dcb91c46fcc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

